repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.11
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.6
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        name: mypy --strict
        args:
          - --strict
          - src/aioairtable
          - tests
        pass_filenames: false
        additional_dependencies:
          - pytest>=9.0.1
          - pytest-asyncio>=1.3.0
          - pytest-mock>=3.15.1,<4
          - hypothesis>=6.148.2,<7
          - aiohttp>=3.13.2,<4
          - multidict>=6.7.0,<7
          - yarl>=1.22.0,<2
          - tenacity>=9.1.2,<10
          - aiofreqlimit>=0.2.2,<0.3
          - msgspec>=0.19.0,<0.20
          - typing_extensions>=4.15.0,<5

  - repo: https://github.com/DetachHead/basedpyright-prek-mirror
    rev: 1.34.0
    hooks:
      - id: basedpyright
        pass_filenames: false

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run --group test pytest
        language: system
        pass_filenames: false
        stages: [commit]
